# Generated by Django 5.0.3 on 2024-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
