# Generated by Django 5.0.3 on 2024-05-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
