# Generated by Django 5.0.3 on 2024-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
