# Generated by Django 5.0.3 on 2024-09-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pedido_precio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
